export const sampleRawCompanyRecords = [
  {
    name: 'Helios Compute',
    description: 'GPU cloud and inference platform built for enterprise AI workloads.',
    website: 'https://helios.example.com',
    founded_year: 2024,
    headquarters: 'Austin, USA',
    funding: 140,
    valuation: 780,
    source_urls: ['https://helios.example.com/news'],
    tags: ['gpu', 'cloud'],
    data_source: 'dev-seed',
  },
  {
    name: 'LexiForge',
    description: 'Legal workflow assistant that automates contract drafting with agents.',
    website: 'https://lexiforge.example.com',
    founded_year: 2025,
    headquarters: 'New York, USA',
    funding: 22,
    valuation: 210,
    tags: ['legal', 'agent'],
    data_source: 'dev-seed',
  },
  {
    name: 'BioSage Labs',
    description: 'Clinical AI company for diagnostic recommendations and biomarker analysis.',
    website: 'https://biosage.example.com',
    founded_year: 2023,
    headquarters: 'Boston, USA',
    funding: 60,
    valuation: 500,
    source_urls: ['https://biosage.example.com/research'],
    tags: ['healthcare'],
    data_source: 'dev-seed',
  },
];
